config/routes.rb
Rails.application.routes.draw do
  root to: 'games#home'

  get 'home', to: 'games#home'

  get 'new', to: 'games#new'

  post 'score', to: 'games#score'

  get 'score', to: 'games#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def home

  end

  def new
    num = params[:num].to_i
    array = ('a'..'z').to_a
    @ran_sam = array.sample(num)
    @start = Time.now
  end

  def score
    @word = params[:word]
    @grid = params[:grid]
    start_time = params[:start].to_i
    finish = Time.now.to_i
    @bool = "The given attempt is " + check_english(@word)
    @bool += in_the_grid?(@grid, @word)
    @time = (finish - start_time) / 3600
    @score = points(@word, start_time, finish)
  end

  def check_english(attempt)
    url = "https://wagon-dictionary.herokuapp.com/#{attempt}"

    uri = URI(url)
    response = Net::HTTP.get(uri)
    user = JSON.parse(response)

    if user["found"]
      "an English word, "
    else
      "not an english word, "
    end
  end

  def in_the_grid?(grid, attempt)
    arr = attempt.upcase.split('')
    if arr.uniq.all? { |x| grid.count(x) >= arr.count(x) }
      "it is in the grid!"
    else
      "it is not in the grid"
    end
  end

  def points(attempt, start_time, end_time)
    attempt.length / (end_time - start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/home.html.erb
<div class="box">
  <div class="item">
    <h1>Welcome!</h1>
  </div>
  <div class="item">
    <h2>With how many letters do you want to play?</h2>
  </div>
  <div class="item">
    <form action="<%= new_path %> ">
      <input type="text" class="form-control" name="num" placeholder="10?">
      <input type="submit" class="form-control" value="num">
    </form>
  </div>
</div>

app/views/games/new.html.erb
<div class="box">
  <div class="headers">
    <h1>Game</h1>
    <p>Find the longest word within the following letters</p>
  </div>
  <div class="elem-holder">
    <% @ran_sam.each do |elem| %>
    <div class="elem">
      <h3> <%= elem %></h3>
    </div>
    <% end %>
  </div>
  <div class="body">
    <form action="<%= score_path %>" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :grid, @ran_sam %>
      <%= hidden_field_tag :start, @start %>
      <input type="text" name="word" placeholder="Longest Word">
      <input type="submit">
    </form>
  </div>
</div>

app/views/games/score.html.erb
<div class="box">
  <div class="item">
    <h1>Result</h1>
    <h3>
      Your answer for the letters was <br>
      <%= @word %>
    </h3>
  </div>
  <div class="item">
    <h2>
      <%= @bool %>
    </h2>
  </div>
  <div class="item">
    <h3><%= @grid %></h3>
  </div>
  <div class="item">
    <h3>
      It took you
      <%= @time %>
      seconds to answer.
    </h3>
  </div>
  <div class="item">
    <h2>
      Your score is:
      <%= @score %>
    </h2>
  </div>
  <a href="<%= root_path %>" class="form-control btn btn-primary">Play again</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>